import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { fixtures, queryFixtures, titles, authors } from '../src/fixtures.mjs';
const root = new URL('../dist/', import.meta.url);
const seed = await readFile(new URL('index.html',root),'utf8');
const pre = seed.slice(0,seed.indexOf('<main id="main">')).replace('noindex,nofollow','noindex,follow').replace('</head>',(seed.includes('assets/pages.css')?'':'<link rel="stylesheet" href="assets/pages.css">')+'</head>');
const foot = '</div>'+seed.slice(seed.indexOf('<footer>'));
const escape = s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const save = async(path,content)=>{const u=new URL(path,root);await mkdir(dirname(fileURLToPath(u)), {recursive:true});await writeFile(u,content,'utf8');};
const prefixFor = path=>'../'.repeat(path.split('?')[0].split('/').length-1);
function layout(path,title,body){const prefix=prefixFor(path);const head=pre.replace(/<title>.*?<\/title>/,`<title>${escape(title)} | 한빛시</title>`).replace(/(href|src)="(?!data:|https?:|#)([^"]+)"/g,(_,attr,url)=>`${attr}="${prefix}${url}"`);return head+`<main id="main"><div class="breadcrumb"><a href="${prefix}index.html">홈</a><span>/</span>시민소통<span>/</span>${escape(title)}</div>${body}</main>`+foot;}
const categoryName = c=>({free:'자유게시판',life:'생활정보',notice:'공지사항'}[c]||'전체');
const postTitle = f=>f.category==='notice'?['시민소통광장 이용 안내','올바른 온라인 정보 이용 안내','10월 시민 프로그램 안내'][f.index%3]:titles[f.index%titles.length];
const element = (f,cls='excerpt')=>`<p class="${cls}"${f.style?` style="${f.style}"`:''}>${escape(f.text)}</p>`;
const box = f=>`<div class="entry-fragment"${f.parentStyle?` style="${f.parentStyle}"`:''}>${element(f)}</div>`;
const titleBlock = (title,sub)=>`<div class="page-title"><div><span class="eyebrow">OUR VOICES, OUR CITY</span><h1>${title}<span class="title-dot">.</span></h1><p>${sub}</p></div><span class="edition">HANBIT<br><b>2026</b></span></div>`;
const rows = (items,prefix='')=>items.map(f=>`<a class="post-row" href="${prefix}${f.path}"><span class="category ${f.category==='free'?'mint':''}">${categoryName(f.category)}</span><div><strong>${escape(postTitle(f))}${f.index<3?' <em class="new-mark">N</em>':''}</strong><small>${authors[f.index%authors.length]} · 2026.09.${String(30-f.index%12).padStart(2,'0')} <span class="row-comments">댓글 ${f.techniques.length?2:1}</span></small></div><span class="row-count">${54+f.index*7}</span></a>`).join('');
const fullFixtures=fixtures.filter(f=>!f.deep);
// Home: real links, not client-side routing; the evaluator has only one entry URL.
const homeBody=seed.slice(seed.indexOf('<main id="main">')+'<main id="main">'.length,seed.indexOf('</main>'));
const homeMain=homeBody.replace(/(<div class="board-tabs">[\s\S]*?<\/div>)[\s\S]*?<\/section>/,`$1${rows(fullFixtures.slice(0,7))}<a class="more-link" href="board/list.html?category=all&page=1">전체 게시글 보기 <span>＋</span></a></section>`);
// Keep the original home header once; do not nest breadcrumbs across rebuilds.
await save('index.html',pre+'<main id="main">'+homeMain+'</main>'+foot);
const ledger=[];
const controls=[];
const entryFor=(f,selector,frames=[])=>({caseId:f.key,page:f.path,name:f.name,selector,frames,text:f.text,techniques:f.techniques,delayMs:f.delay||0});
for(const f of fixtures){
 const prefix=prefixFor(f.path);let injected='';let scripts='';let frames=[];let selector='div.article-body > div.entry-fragment > p.excerpt';
 if(f.frameDepth){
  const outer=`widgets/community-${f.postId}.html`,inner=`widgets/detail-${f.postId}.html`;
  const frameDoc=body=>`<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>이웃 소식</title><link rel="stylesheet" href="../assets/site.css"><link rel="stylesheet" href="../assets/pages.css"></head><body class="widget-body"><div class="widget-title">이웃이 전하는 소식</div>${body}</body></html>`;
  frames=[{src:outer,selector:'iframe.community-widget'}];selector='div.widget-content > p.excerpt';
  if(f.frameDepth===2){frames.push({src:inner,selector:'iframe.detail-widget'});await save(outer,frameDoc(`<iframe class="detail-widget" src="detail-${f.postId}.html" title="동네 소식 상세"></iframe>`));await save(inner,frameDoc(`<div class="widget-content">${element(f)}</div>`));}
  else await save(outer,frameDoc(`<div class="widget-content">${element(f)}</div>`));
  const html=`<iframe class="community-widget" src="${prefix}${outer}" title="이웃 소식 모음"></iframe>`;
  injected='<div class="embedded-content">'+(f.delay?'':html)+'</div>';
  if(f.delay)scripts=`<script>setTimeout(()=>{document.querySelector('.embedded-content').innerHTML=${JSON.stringify(html)}},${f.delay});</script>`;
 } else if(f.delay){selector='section.comments > div.comment-list > div.comment-item:nth-of-type(2) > p.excerpt';scripts=`<script>setTimeout(()=>{const row=document.createElement('div');row.className='comment-item';row.innerHTML=${JSON.stringify('<span class="comment-author">새로운 이웃</span>'+element(f))};document.querySelector('.comment-list').append(row);document.querySelector('.comment-total').textContent='2';},${f.delay});</script>`;}
 else if(f.repeat){injected=`<div class="entry-fragment"><p class="excerpt">좋은 정보를 나눠주셔서 감사합니다.</p>${element(f)}<p class="excerpt">산책로 이용 시 안전에 유의해 주세요.</p></div>`;selector='div.article-body > div.entry-fragment > p.excerpt:nth-of-type(2)';}
 else injected=box(f);
 const fentry=entryFor(f,selector,frames);(f.techniques.length?ledger:controls).push(fentry);
 const prev=fixtures[Math.max(0,f.index-1)],next=fixtures[Math.min(fixtures.length-2,f.index+1)];
 const body=titleBlock(categoryName(f.category),'시민의 이야기가 모여 한빛의 내일이 됩니다.')+`<article class="article"><div class="article-heading"><span class="category mint">${categoryName(f.category)}</span><h2>${escape(postTitle(f))}</h2><div class="article-meta"><span>${authors[f.index%authors.length]}</span><span>2026.09.${String(30-f.index%12).padStart(2,'0')}</span><span>조회 ${54+f.index*7}</span><span>게시글 ${f.postId}</span></div></div><div class="article-body"><p>안녕하세요, 한빛 시민 여러분. 요즘 우리 동네의 일상을 함께 나누고 싶어 글을 남깁니다.</p><p>한빛천 산책길과 공공도서관, 마을 정원까지 가까운 곳에서 즐길 수 있는 공간이 많아졌습니다. 이용하신 분들의 경험과 의견도 들려주세요.</p>${injected}<p>서로에게 도움이 되는 따뜻한 소통이 이어지면 좋겠습니다. 모두 편안한 하루 보내세요.</p><div class="article-note">시민이 자유롭게 작성한 게시글입니다. 개인정보가 포함되지 않도록 유의해 주세요.</div></div></article><section class="comments"><h3>댓글 <span class="comment-total">1</span></h3><div class="comment-list"><div class="comment-item"><span class="comment-author">한빛이웃</span><p>우리 동네 소식 감사합니다. 저도 주말에 다녀와야겠어요.</p><small>2026.09.30</small></div></div></section><div class="article-actions"><a class="button outline" href="${prefix}board/list.html?category=all&page=1">목록으로</a></div><nav class="adjacent-posts" aria-label="다른 게시글"><a href="${prefix}${prev.path}"><span>이전 글</span>${escape(postTitle(prev))}</a><a href="${prefix}${next.path}"><span>다음 글</span>${escape(postTitle(next))}</a></nav>${scripts}`;
 await save(f.path,layout(f.path,postTitle(f),body));
}
// URL query values are significant; only ordering and fragments are duplicates.
const queryArticle = f=>`<article class="article"><div class="article-heading"><span class="category">시민 제안</span><h2>${f.postId==='1024'?'시민광장 야간 이용에 관한 제안':'문화센터 프로그램 참여 후기'}</h2><div class="article-meta">마을친구 · 2026.09.28 · 게시글 ${f.postId}</div></div><div class="article-body"><p>누구나 편리하게 이용할 수 있는 시민 공간을 제안합니다.</p>${box(f)}<p>시민 여러분의 의견을 들려주세요.</p></div></article>`;
await save('board/view.html',layout('board/view.html','시민 제안',titleBlock('시민 제안','작은 의견이 모여 더 좋은 일상을 만듭니다.')+'<div id="article-slot"></div><a class="button outline" href="list.html?category=all&page=1">목록으로</a><script src="../assets/view.js"></script>'));
await save('assets/view.js',`const articles=${JSON.stringify(Object.fromEntries(queryFixtures.map(f=>[f.postId,queryArticle(f)])))};const id=new URLSearchParams(location.search).get('id');document.querySelector('#article-slot').innerHTML=articles[id]||'<div class="empty-state">게시글을 찾을 수 없습니다.</div>';`);
queryFixtures.forEach(f=>ledger.push(entryFor(f,'div.article-body > div.entry-fragment > p.excerpt')));
// Listing is finite: four pages, bounded search and no random/infinitely generated links.
await save('board/list.html',layout('board/list.html','게시판',titleBlock('시민소통광장','한빛의 소식부터 우리 동네 이야기까지, 함께 나눠요.')+`<form class="search-form" role="search"><label for="board-search">게시글 검색</label><input id="board-search" name="q" type="search" placeholder="어떤 이야기를 찾으시나요?" maxlength="80"><button class="button" type="submit">검색</button></form><div class="board-tabs" id="list-tabs"></div><div class="list-summary"><span>총 <b id="result-count">44</b>개의 이야기</span><span id="page-label"></span></div><div id="post-list"></div><nav class="pagination" aria-label="게시판 페이지" id="pagination"></nav><div class="related-box"><strong>시민 제안 모아보기</strong><a href="view.html?id=1024&mode=public">시민광장 야간 이용에 관한 제안</a><a href="view.html?id=1180&mode=public">문화센터 프로그램 참여 후기</a><a href="view.html?mode=public&id=1024#opinion">시민광장 제안의 의견 보기</a></div><script src="../assets/list.js"></script>`));
const listRecords=fullFixtures.map(f=>({path:'../'+f.path,title:postTitle(f),category:f.category,author:authors[f.index%authors.length],id:f.postId,index:f.index}));
await save('assets/list.js',`const records=${JSON.stringify(listRecords)};const names={all:'전체',free:'자유게시판',life:'생활정보',notice:'공지사항'};const p=new URLSearchParams(location.search);const category=Object.hasOwn(names,p.get('category'))?p.get('category'):'all';let page=Math.max(1,parseInt(p.get('page')||'1',10)||1);let query=p.get('q')||'';const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const url=(c,n,q='')=>'list.html?category='+c+'&page='+n+(q?'&q='+encodeURIComponent(q):'');function render(){const filtered=records.filter(r=>(category==='all'||r.category===category)&&r.title.includes(query));const pages=Math.max(1,Math.ceil(filtered.length/12));page=Math.min(page,pages);document.querySelector('#result-count').textContent=filtered.length;document.querySelector('#page-label').textContent=page+' / '+pages+' 페이지';document.querySelector('#list-tabs').innerHTML=Object.entries(names).map(([c,n])=>'<a class="'+(c===category?'active':'')+'" href="'+url(c,1)+'">'+n+'</a>').join('');document.querySelector('#post-list').innerHTML=filtered.slice((page-1)*12,page*12).map(r=>'<a class="post-row" href="'+r.path+'"><span class="category">'+names[r.category]+'</span><div><strong>'+esc(r.title)+'</strong><small>'+r.author+' · 2026.09.30 · '+r.id+'</small></div><span class="row-count">'+(54+r.index*7)+'</span></a>').join('')||'<div class="empty-state">검색 결과가 없습니다. 다른 검색어를 입력해 주세요.</div>';document.querySelector('#pagination').innerHTML=Array.from({length:pages},(_,i)=>'<a '+(page===i+1?'aria-current="page"':'')+' href="'+url(category,i+1,query)+'">'+(i+1)+'</a>').join('');}document.querySelector('#board-search').value=query;document.querySelector('.search-form').addEventListener('submit',e=>{e.preventDefault();query=document.querySelector('#board-search').value.trim();page=1;history.replaceState(null,'',url(category,page,query));render();});render();`);
await save('culture/index.html',layout('culture/index.html','문화·행사',titleBlock('문화가 있는 한빛','가까운 곳에서 만나는 새로운 즐거움.')+`<section class="event-feature"><span class="eyebrow">2026 HANBIT CULTURE WEEK</span><h2>한빛의 가을,<br>문화가 되다.</h2><p>2026. 10. 09. — 10. 18. · 시민광장 · 한빛문화센터</p><div class="event-program"><article><b>09</b><h3>시민 음악 산책</h3><p>금요일 18:00 · 시민광장</p></article><article><b>12</b><h3>책과 함께하는 오후</h3><p>월요일 14:00 · 작은도서관</p></article><article><b>18</b><h3>우리 마을 이야기</h3><p>일요일 15:00 · 문화센터</p></article></div></section><div class="related-box"><strong>지난 소식</strong><a href="../archive/index.html">시민 이야기 아카이브</a></div>`));
await save('archive/index.html',layout('archive/index.html','시민 이야기 아카이브',titleBlock('시민 이야기 아카이브','우리 동네에 쌓인 기록을 만나보세요.')+'<div class="related-box"><a href="2026/index.html">2026년 시민 이야기</a></div>'));
await save('archive/2026/index.html',layout('archive/2026/index.html','2026년 시민 이야기',titleBlock('2026년의 기록','계절마다 달라지는 한빛의 일상.')+'<div class="related-box"><a href="autumn/index.html">가을 이야기 모음</a></div>'));
await save('archive/2026/autumn/index.html',layout('archive/2026/autumn/index.html','가을 이야기',titleBlock('가을의 기록','새로운 이웃의 이야기가 도착하고 있어요.')+'<div class="related-box" id="archive-items"><p>소식을 불러오고 있습니다.</p></div><script>setTimeout(()=>{document.querySelector("#archive-items").innerHTML=\'<a href="read.html">가을 저녁, 마을에서 나눈 이야기</a>\'},950)</script>'));
await save('guide/index.html',layout('guide/index.html','광장 이용 안내',titleBlock('함께 지키는 소통 예절','서로 다른 생각이 만나 더 좋은 도시가 됩니다.')+`<div class="guide-content"><h2>존중하는 말, 따뜻한 대화</h2><p>서로의 의견을 존중하고 개인정보를 공개하지 않도록 유의해 주세요.</p><h2>불법광고에 주의하세요</h2><p>도박, 불법 대출, 의약품 불법 판매 등을 유도하는 광고를 발견하면 신고해 주세요. 카지노 가입 보너스, 선입금 대출과 같은 문구가 포함된 의심스러운 링크를 누르지 마세요.</p><h2>가상 웹사이트 안내</h2><p>이 사이트의 기관명, 시민 게시글, 행사와 광고 문구는 탐지 도구 검증용 합성 자료입니다. 실제 신청이나 거래 기능은 제공하지 않습니다.</p><p><a href="https://example.invalid/hanbit-info" rel="nofollow noopener">외부 참고 링크 (검증용 비연결 주소)</a></p></div>`));
await save('robots.txt','User-agent: *\nAllow: /\nDisallow: /lab/\n');
const manifest={version:'1.0.0',entry:'index.html',fixtureViewport:{width:1440,height:1000},maxInjectionDelayMs:2800,scope:'요강 기반 자체 정답. 주최 측 비공개 정답셋과 무관.',urlPolicy:'query values preserved; query ordering and fragment ignored',iframeUrlPolicy:'findings.url is the top document URL; location contains absolute iframe src chain',cases:ledger,negativeControls:controls};
await mkdir(new URL('../reference/',import.meta.url),{recursive:true});await writeFile(new URL('../reference/ground-truth.json',import.meta.url),JSON.stringify(manifest,null,2)+'\n');
await save('lab/manifest.json',JSON.stringify(manifest));
console.log(JSON.stringify({posts:fixtures.length+queryFixtures.length,positiveElements:ledger.length,expectedFindings:ledger.reduce((n,f)=>n+f.techniques.length,0),negativeControls:controls.length,output:'dist'}));
